config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  resources :pedidos
  resources :items
  resources :funcionarios
  resources :fornecedors
  resources :comandas do
    member do
      get 'cancelar_pedido'
      get 'finalizar_pedido'
      post 'encerrar'
      post 'new_pedido'
    end
  end
  post 'comandas/create'
  get 'sessions/new'

  
  root                'static_pages#home'
  get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  
  
  get 'fornecedor/search' => 'fornecedors#search'
  post 'fornecedor/search' => 'fornecedors#search', as: :fornecedors_search
  get 'fornecedor/relatorio/:id' => 'fornecedors#relatorio', as: :fornecedors_relatorio
  get 'fornecedor/del_fornecedor/:id', to: 'fornecedors#destroy', as: :fornecedor_delete
  
  
  get 'funcionario/search' => 'funcionarios#search'
  post 'funcionario/search' => 'funcionarios#search', as: :funcionarios_search
  get 'funcionario/demitir/:id' => 'funcionarios#demitir', as: :funcionarios_demitir

  get 'pedidos' => 'pedidos#index', as: :pedido_index
  get 'pedido/:id' => 'pedidos#show', as: :pedido_show
  get 'pedido/:id/finalizar_pedido' => 'pedidos#finalizar_pedido', as: :pedido_encerrar
  
  get 'compra/item_index', to: 'compra#item_index', as: :item_index
  post 'compra/item_index', to: 'compra#item_index'
  post 'compra/item(/:id)', to: 'compra#item_create'
  patch 'compra/item/:id', to: 'compra#item_update'
  get 'compra/item(/:id)', to: 'compra#item_show', as: :item_show
  get 'compra/item_new', to: 'compra#item_new', as: :item_new
  get 'compra/item/:id/edit', to: 'compra#item_edit', as: :item_edit
  get 'compra/delitem/:id', to: 'compra#item_destroy', as: :item_delete
  get 'compra/relatorio_itens_falta' => 'compra#relatorio_itens_falta', as: :itens_falta_relatorio

  get 'compra/vende_index', to: 'compra#index', as: :vende_index
  post 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#create'
  patch 'compra/vende/:id1/:id2/:id3', to: 'compra#update'
  get 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#show', as: :vende_show
  get 'compra/vende_new', to: 'compra#new', as: :vende_new
  get 'compra/vende/:id1/:id2/:id3/edit', to: 'compra#edit', as: :vende_edit
  get 'compra/delvende/:id1/:id2/:id3', to: 'compra#destroy', as: :vende_delete

  get 'produtos/index', to: 'produtos#index', as: :produto_index
  post 'produtos(/:id)', to: 'produtos#create'
  patch 'produtos/:id', to: 'produtos#update'
  get 'produtos/new', to: 'produtos#new', as: :produto_new
  get 'produtos(/:id)', to: 'produtos#show', as: :produto_show
  get 'produtos/:id/edit', to: 'produtos#edit', as: :produto_edit
  get 'produtos/delproduto/:id', to: 'produtos#destroy', as: :produto_delete

  get 'produto/:produto_id/componentes_index', to: 'produtos#componentes_index', as: :componentes_index
  post 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_create'
  patch 'produto/componentes/:id1/:id2/:id3', to: 'produtos#componentes_update'
  get 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_show', as: :componentes_show
  get 'produtos/componentes_new', to: 'produtos#componentes_new', as: :componentes_new
  get 'produtos/componentes/:id1/:id2/:id3/edit', to: 'produtos#componentes_edit', as: :componentes_edit
  get 'produto/componentes/delcomponente/:id', to: 'produtos#componentes_destroy', as: :componentes_delete

end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  include ApplicationHelper
  before_action do redirecionar_privilegio(3) end
  before_action :set_pedido, only: [:show, :edit, :update, :destroy, :finalizar_pedido]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
	@funcionarios = Funcionario.all
	@comandas = Comanda.all
	@produtos = Produto.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  def finalizar_pedido
	if(@pedido.dataFinalizacao == nil)
		@pedido.dataFinalizacao = Time.now.strftime("%Y-%m-%d %H:%M:%S")
		@pedido.save
    end
	respond_to do |format|
      format.html { redirect_to pedido_index_path, notice: 'Pedido concluido com sucesso' }
      format.json { head :no_content }
    end
  end
  
  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:idPedido, :idFuncionario, :idProduto, :idcomanda, :dataPedido, :dataFinalizacao, :cancelado)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Lista de pedidos</span>
		</div>
	</div>

	<table class="table table-hover">
		<thead>
			<tr>
				<th>Funcionário</th>
				<th>Mesa</th>
				<th>Produto</th>

				<th>Hora do pedido</th>
				<th>Hora finalização</th>
				<th>Estado</th>
				<th>Opções</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @pedidos.each do |pedido| %>
				<tr>
					<td><%= @funcionarios.find(pedido.idFuncionario).nome%></td>
					<td><%= @comandas.find(pedido.idcomanda).mesa %></td>
					<td><%= @produtos.find(pedido.idProduto).nome %></td>
					<td align = "center"><%= pedido.dataPedido.strftime("%H:%M")%></td>
					<td align = "center">
						<%if (pedido.dataFinalizacao != nil)%>
							<%= pedido.dataFinalizacao.strftime("%H:%M") %>
						<%end%>
					</td>
					<td>
						<%if (pedido.cancelado)%>
							cancelado
						<%elsif(pedido.dataFinalizacao != nil)%>
							finalizado
						<%end%>
					</td>
					
					<td align = "right"> <a href = <%= pedido_show_path(pedido)%>> <span class="glyphicon glyphicon-log-in" title="Detalhes"> </a></td>
					<td align = "center"> <a href = <%= pedido_encerrar_path(pedido)%>> <span class="glyphicon glyphicon-check" title="Finalizar"> </a></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="portlet light">
	<div class="portlet-title">
		<div class="caption font-blue-sunglo">
			<span class="caption-subject bold uppercase">Detalhes do pedido</span>
		</div>
	</div>
	<p>
		<strong>Idpedido:</strong>
		<%= @pedido.idPedido %>
	</p>

	<p>
		<strong>Idfuncionario:</strong>
		<%= @pedido.idFuncionario %>
	</p>

	<p>
		<strong>Idproduto:</strong>
		<%= @pedido.idProduto %>
	</p>

	<p>
		<strong>Idcomanda:</strong>
		<%= @pedido.idcomanda %>
	</p>

	<p>
		<strong>Datapedido:</strong>
		<%= @pedido.dataPedido %>
	</p>

	<p>
		<strong>Datafinalizacao:</strong>
		<%= @pedido.dataFinalizacao %>
	</p>

	<p>
		<strong>Cancelado:</strong>
		<%= @pedido.cancelado %>
	</p>

	<%= button_to "Voltar", pedidos_path, :class => "btn btn-default", :method => :get  %>
</div>