config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  resources :pedidos
  resources :items
  resources :funcionarios
  resources :fornecedors
  resources :comandas do
    member do
      get 'cancelar_pedido'
      get 'finalizar_pedido'
      post 'encerrar'
      post 'new_pedido'
    end
  end
  post 'comandas/create'
  get 'sessions/new'

  
  root                'static_pages#home'
  get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  
  
  get 'fornecedor/search' => 'fornecedors#search'
  post 'fornecedor/search' => 'fornecedors#search', as: :fornecedors_search
  get 'fornecedor/relatorio/:id' => 'fornecedors#relatorio', as: :fornecedors_relatorio
  get 'fornecedor/del_fornecedor/:id', to: 'fornecedors#destroy', as: :fornecedor_delete
  
  
  get 'funcionario/search' => 'funcionarios#search'
  post 'funcionario/search' => 'funcionarios#search', as: :funcionarios_search
  get 'funcionario/demitir/:id' => 'funcionarios#demitir', as: :funcionarios_demitir

  get 'pedidos' => 'pedidos#index', as: :pedido_index
  get 'pedido/:id' => 'pedidos#show', as: :pedido_show
  get 'pedido/:id/finalizar_pedido' => 'pedidos#finalizar_pedido', as: :pedido_encerrar
  
  get 'compra/item_index', to: 'compra#item_index', as: :item_index
  post 'compra/item_index', to: 'compra#item_index'
  post 'compra/item(/:id)', to: 'compra#item_create'
  patch 'compra/item/:id', to: 'compra#item_update'
  get 'compra/item(/:id)', to: 'compra#item_show', as: :item_show
  get 'compra/item_new', to: 'compra#item_new', as: :item_new
  get 'compra/item/:id/edit', to: 'compra#item_edit', as: :item_edit
  get 'compra/delitem/:id', to: 'compra#item_destroy', as: :item_delete
  get 'compra/relatorio_itens_falta' => 'compra#relatorio_itens_falta', as: :itens_falta_relatorio

  get 'compra/vende_index', to: 'compra#index', as: :vende_index
  post 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#create'
  patch 'compra/vende/:id1/:id2/:id3', to: 'compra#update'
  get 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#show', as: :vende_show
  get 'compra/vende_new', to: 'compra#new', as: :vende_new
  get 'compra/vende/:id1/:id2/:id3/edit', to: 'compra#edit', as: :vende_edit
  get 'compra/delvende/:id1/:id2/:id3', to: 'compra#destroy', as: :vende_delete

  get 'produtos/index', to: 'produtos#index', as: :produto_index
  post 'produtos(/:id)', to: 'produtos#create'
  patch 'produtos/:id', to: 'produtos#update'
  get 'produtos/new', to: 'produtos#new', as: :produto_new
  get 'produtos(/:id)', to: 'produtos#show', as: :produto_show
  get 'produtos/:id/edit', to: 'produtos#edit', as: :produto_edit
  get 'produtos/delproduto/:id', to: 'produtos#destroy', as: :produto_delete

  get 'produto/:produto_id/componentes_index', to: 'produtos#componentes_index', as: :componentes_index
  post 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_create'
  patch 'produto/componentes/:id1/:id2/:id3', to: 'produtos#componentes_update'
  get 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_show', as: :componentes_show
  get 'produtos/componentes_new', to: 'produtos#componentes_new', as: :componentes_new
  get 'produtos/componentes/:id1/:id2/:id3/edit', to: 'produtos#componentes_edit', as: :componentes_edit
  get 'produto/componentes/delcomponente/:id', to: 'produtos#componentes_destroy', as: :componentes_delete

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  has_many :pedidos, primary_key: "idPedido", foreign_key: "idPedido"
  has_many :comandas, through: :pedidos
  has_many :componentes_produtos, primary_key: "idProduto", foreign_key: "idProduto", :dependent => :delete_all
  has_many :items, through: :componentes_produtos

  validates_presence_of :nome, :on => :create, :message => "O campo nome deve ser informado"
  validates_presence_of :valor, :on => :create, :message => "O campo valor deve ser informado"
  validates_presence_of :descricao, :on => :create, :message => "O campo descricao deve ser informado"

  def quantidade
    componentes = self.componentes_produtos

    menor_quantidade = -1;
    componentes.each do |componente|
      if(menor_quantidade == -1)
        menor_quantidade = componente.item.quantidade / componente.quantidade
      else
        quantidade_temporaria = componente.item.quantidade / componente.quantidade
        menor_quantidade = menor_quantidade > quantidade_temporaria ? quantidade_temporaria : menor_quantidade;
      end
    end
    return menor_quantidade > -1 ? menor_quantidade : 0
  end

end

app/controllers/produtos_controller.rb
# coding: utf-8
require 'json'
class ProdutosController < ApplicationController
  include ApplicationHelper
  before_action only: [:new, :create, :update, :edit, :destroy] do redirecionar_privilegio(0) end
  before_action do redirecionar_privilegio(2) end
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  before_action :set_componentes_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all.order :nome
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
    @componentes_produto = @produto.componentes_produtos
    @items = Item.all
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
    @componentes_produto = @produto.componentes_produtos
    puts "[Aqui]"
    puts "linha #{@componentes_produto.class}"
    puts"[Nao aqui]"
    @items = Item.all
  end

  # POST /produtos
  # POST /produtos.json
  def create
    Produto.transaction do
      @produto = Produto.new(produto_params)
      items = JSON.parse(params["items"])
      respond_to do |format|
        if @produto.save
          items.each do |it|
            componentes_produto = ComponentesProduto.new
            componentes_produto.idProduto = @produto.idProduto
            componentes_produto.idItem = it["id"]
            componentes_produto.quantidade = it["quantidade"]
            componentes_produto.save
          end
          format.html { redirect_to @produto, notice: 'Produto criado com sucesso.' }
          format.json { render :show, status: :created, location: @produto }
        else
          format.html { render :new }
          format.json { render json: @produto.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    Produto.transaction do
      @produto =  Produto.find(params[:id])
      items = JSON.parse(params["items"])      
      respond_to do |format|
        if @produto.update(produto_params)
          items.each do |it|
            if !@produto.componentes_produtos.any? {|c| c["idItem"] == it["id"]}
              componentes_produto = ComponentesProduto.new
              componentes_produto.idProduto = @produto.idProduto
              componentes_produto.idItem = it["id"]
              componentes_produto.quantidade = it["quantidade"]
              componentes_produto.save
            end
          end

          @produto.componentes_produtos.each do |cp|
            if !items.any? {|i| i["id"] == cp["idItem"]}
              cp.destroy
            end
          end
          
          format.html { redirect_to @produto, notice: 'Produto foi atualizado com sucesso.' }
          format.json { render :show, status: :ok, location: @produto }
        else
          format.html { render :edit }
          format.json { render json: @produto.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy

    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto foi deletado com sucesso.' }
      format.json { head :no_content }
    end
  end


# Controlador Componente Protudo.

  # GET /componentes_produtos
  # GET /componentes_produtos.json
  def componentes_index
    @componentes_produtos = ComponentesProduto.all
  end

  # GET /componentes_produtos/1
  # GET /componentes_produtos/1.json
  def componentes_show
  end

  # GET /componentes_produtos/new
  def componentes_new
    @componentes_produto = ComponentesProduto.new
  end

  # GET /componentes_produtos/1/edit
  def componentes_edit
  end

  def componentes_adicionar
  end


  # POST /componentes_produtos
  # POST /componentes_produtos.json
  def componentes_create
    puts "Começa"
    puts params
    teste = JSON.parse(params["items"])
    # @lista_componentes.push({idItem: params['componentes_produto']['idItem'],
    #                          quantidade: params['componentes_produto']['quantidade']})
    # @lista_componentes.each do |x|
    #   puts "Valor: #{x} ."
    # end
    puts "termina"

    respond_to do |format|
        format.html { redirect_to :back, notice: 'Componente criado com sucesso.' }
        #format.json { render :componentes_show, status: :created, location: @componentes_produto }
    end
    
    # @componentes_produto = ComponentesProduto.new(componentes_produto_params)

    # respond_to do |format|
    #   if @componentes_produto.save
    #     format.html { redirect_to :back, notice: 'Componente criado com sucesso.' }
    #     format.json { render :show, status: :created, location: @componentes_produto }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @componentes_produto.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /componentes_produtos/1
  # PATCH/PUT /componentes_produtos/1.json
  def componentes_update
    respond_to do |format|
      if @componentes_produto.update(componentes_produto_params)
        format.html { redirect_to @componentes_produto, notice: 'Componente foi atualizado com sucesso' }
        format.json { render :show, status: :ok, location: @componentes_produto }
      else
        format.html { render :edit }
        format.json { render json: @componentes_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /componentes_produtos/1
  # DELETE /componentes_produtos/1.json
  def componentes_destroy
    @componentes_produto = ComponentesProduto.find(params[:id])
    @componentes_produto.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Componente foi deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_componentes_produto
      #@componentes_produto = ComponentesProduto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def componentes_produto_params
      params.require(:componentes_produto).permit(:idCompoe, :idProduto, :idItem, :quantidade)
    end

    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :valor, :descricao)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, url: produto_show_path(@produto), id: "new_produto") do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% @produto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="portlet light ">
    <div class="portlet-body form">
      <form role="form">
        <div class="form-body">
          <div class="form-group">
            <div>
              <%= f.label :nome, class: "control-label" %>
              <%= f.text_field :nome, class: "form-control input-xlarge" %>
            </div>
            <br>
            <div>
              <%= f.label :valor,class: "control-label" %><br>
              <%= f.text_field :valor, class: "form-control  input-xlarge"   %>
            </div>
            <br>
            <div>
              <%= f.label :descricao, class: "control-label" %><br>
              <%= f.text_field :descricao, class: "form-control  input-xlarge"   %>
            </div>  
            <br>
              
              <table id="tabela-selecionados" class="table table-hover">
                <thead>
                  <tr>
                    <th style="width: 130px;">Nome</th>
                    <th style="width: 130px;">Marca</th>
                    <th style="width: 70px;">Quantidade</th>
                    <th style="width: 70px;"><th>
                  </tr>
                </thead>
                <br>
                <tbody>

                  <% for i in (0 ... @componentes_produto.length) do %>
                    <tr id="<%= @componentes_produto[i].idItem %>}">
                      <td> <%= @componentes_produto[i].item.nome %> </td>
                      <td> <%= @componentes_produto[i].item.marca %> </td>
                      <td> <%= @componentes_produto[i].quantidade %> </td>
                      <td> <input type="button" value="Excluir" class="btn red" onClick="pdtRemoverItem(this.parentNode.parentNode.rowIndex)" /></td>
                    </tr>
                  <% end %>
                  
                  <% @items.each do |item| %>
                    
                    <tr style="display: none">
                      <td><%= item.nome %></td>
                      <td><%= item.marca %></td>
                      <td></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

              <div class="actions">
                <a class="btn green" data-toggle="modal" href="#nova-comanda">
                  <i class="fa fa-plus-circle"></i>Adicionar Item
                </a>
              </div>
              <!--   
                   <div class="field">
                   <%#= f.label :idCompoe %><br>
                   <%#= f.number_field :idCompoe %>
                   </div>
                   <div class="field">
                   <%#= f.label :idProduto %><br>
                   <%#= f.number_field :idProduto %>
                   </div>
                   <div class="field">
                   <%#= f.label :idItem %><br>
                   <%#= f.number_field :idItem %>
                   </div>
                   <div class="field">
                   <%#= f.label :quantidade %><br>
                   <%#= f.number_field :quantidade %>
                   </div>
                   <div class="actions">
                   <%#= f.submit %>
                   </div> 
                 -->
            <br><br>

            <div class="actions">
              <%= f.submit :class => "btn green", id: "cdstr" %><br>
              <%#= link_to "Teste", "#", class: "btn green", onclick: "cadastrar()", remote: true %>
            </div>
            <hr> 
          </div>
        </div>
      </form>

    </div>
  </div>

<% end %>




<div id="nova-comanda" class="modal fade" tabindex="-1" data-width="600" style="display: none; width: 600px; margin-left: -379px; margin-top: 0px;" aria-hidden="true">

  <%= form_tag('/produtos/create', method: "post", class:'form-horizontal') do |f| %>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
      <h2 class="modal-title">Lista de Itens</h2>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="form-body">
          <div class="col-md-12">
            <div class="form-group">
              <div id="alert_container" class="custom-alerts alert alert-danger fade in" style="display: none;"><button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>Voce precisa definir a quantidade dos itens selecionados</div>

              <table id="lista-de-itens" class="table table-hover">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Marca</th>
                    <th>Quantidade</th>
                  </tr>
                </thead>
                <tbody>
                  <% @items.each do |item| %>
                    <tr>
                      <td>
                        <input type="checkbox" onchange="pdtItemAlterado(this)" value="<%= item.id %>" <%= "checked" if @componentes_produto.any? {|c| c["idItem"] == item.id} %> >
                      </td>
                      <td><%= item.nome %></td>
                      <td><%= item.marca %></td>
                      <td style="width: 70px;"><input type="number" min="0" name="quantidade" class="form-control" value ="<%= @componentes_produto.find {|c| c["idItem"] == item.id}.nil? ? 0 : @componentes_produto.find {|c| c["idItem"] == item.id}["quantidade"] %>" /></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>

            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <input type="button" class="btn green" onclick="pdtChecarItensSelecionados()" aria-hidden="true" value="Adicionar"/>
    </div>
  <%end%>
</div>

app/views/produtos/edit.html.erb
<div class="portlet-title">
    <div class="caption">
        <i class=" font-green-sharp"></i>
        <span class="caption-subject font-green-sharp bold uppercase"><h3>Editar Produto</h3></span>
    </div>
</div>

<%= render 'form' %>


<div class="actions">
    <a class="btn btn-default" data-toggle="modal" href=<%=produto_show_path(@produto)%>>
        Mostrar
    </a>
    
    <a class="btn btn-default" data-toggle="modal" href= <%=produtos_path%>>
        Voltar
    </a>
</div>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<div class="portlet-title">
    <div class="caption">
        <i class=" font-green-sharp"></i>
        <span class="caption-subject font-green-sharp bold uppercase"><h3>Lista de Produtos</h3> </span>
    </div>
</div>

<div class="portlet light ">
  <div class="portlet-body form">
  <form role="form">
    <div class="form-body">
      <div class="form-group">

        <table class="table table-hover">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Valor</th>
              <th>Descricao</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @produtos.each do |produto| %>
            <tr>
              <td><%= produto.nome %></td>
              <td><%= produto.valor %></td>
              <td><%= produto.descricao %></td>
        	    
              <td align = "right"> <a href = <%= produto_show_path(produto)%>> <span class="glyphicon glyphicon-log-in" title="Detalhes"> </a></td>
              <td align = "center"> <a href = <%= produto_edit_path(produto)%>> <span class="glyphicon glyphicon-edit" title="Modificar"> </a></td>
              <td align = "center"> <a href = <%= produto_delete_path(produto)%>> <span class="glyphicon glyphicon-remove" title="Remover"> </a></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </form>
  </div>
</div>

<br>
<div class="actions">
  <a class="btn green" data-toggle="modal" href= <%=produto_new_path%>>
    <i class="fa fa-plus-circle"></i>Novo Produto
  </a>
</div>

app/views/produtos/new.html.erb
<div class="portlet-title">
    <div class="caption">
        <i class=" font-green-sharp"></i>
        <span class="caption-subject font-green-sharp bold uppercase"><h3>Novo Produto</h3></span>
    </div>
</div>

<%= render 'form' %>

<div class="actions">
  <a class="btn btn-default" data-toggle="modal" href= <%=produto_index_path%> >
        Voltar
    </a>
</div>