config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  resources :pedidos
  resources :items
  resources :funcionarios
  resources :fornecedors
  resources :comandas do
    member do
      get 'cancelar_pedido'
      get 'finalizar_pedido'
      post 'encerrar'
      post 'new_pedido'
    end
  end
  post 'comandas/create'
  get 'sessions/new'

  
  root                'static_pages#home'
  get    'home'    => 'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  
  
  get 'fornecedor/search' => 'fornecedors#search'
  post 'fornecedor/search' => 'fornecedors#search', as: :fornecedors_search
  get 'fornecedor/relatorio/:id' => 'fornecedors#relatorio', as: :fornecedors_relatorio
  get 'fornecedor/del_fornecedor/:id', to: 'fornecedors#destroy', as: :fornecedor_delete
  
  
  get 'funcionario/search' => 'funcionarios#search'
  post 'funcionario/search' => 'funcionarios#search', as: :funcionarios_search
  get 'funcionario/demitir/:id' => 'funcionarios#demitir', as: :funcionarios_demitir

  get 'pedidos' => 'pedidos#index', as: :pedido_index
  get 'pedido/:id' => 'pedidos#show', as: :pedido_show
  get 'pedido/:id/finalizar_pedido' => 'pedidos#finalizar_pedido', as: :pedido_encerrar
  
  get 'compra/item_index', to: 'compra#item_index', as: :item_index
  post 'compra/item_index', to: 'compra#item_index'
  post 'compra/item(/:id)', to: 'compra#item_create'
  patch 'compra/item/:id', to: 'compra#item_update'
  get 'compra/item(/:id)', to: 'compra#item_show', as: :item_show
  get 'compra/item_new', to: 'compra#item_new', as: :item_new
  get 'compra/item/:id/edit', to: 'compra#item_edit', as: :item_edit
  get 'compra/delitem/:id', to: 'compra#item_destroy', as: :item_delete
  get 'compra/relatorio_itens_falta' => 'compra#relatorio_itens_falta', as: :itens_falta_relatorio

  get 'compra/vende_index', to: 'compra#index', as: :vende_index
  post 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#create'
  patch 'compra/vende/:id1/:id2/:id3', to: 'compra#update'
  get 'compra/vende((/:id1)(/:id2)(/:id3))', to: 'compra#show', as: :vende_show
  get 'compra/vende_new', to: 'compra#new', as: :vende_new
  get 'compra/vende/:id1/:id2/:id3/edit', to: 'compra#edit', as: :vende_edit
  get 'compra/delvende/:id1/:id2/:id3', to: 'compra#destroy', as: :vende_delete

  get 'produtos/index', to: 'produtos#index', as: :produto_index
  post 'produtos(/:id)', to: 'produtos#create'
  patch 'produtos/:id', to: 'produtos#update'
  get 'produtos/new', to: 'produtos#new', as: :produto_new
  get 'produtos(/:id)', to: 'produtos#show', as: :produto_show
  get 'produtos/:id/edit', to: 'produtos#edit', as: :produto_edit
  get 'produtos/delproduto/:id', to: 'produtos#destroy', as: :produto_delete

  get 'produto/:produto_id/componentes_index', to: 'produtos#componentes_index', as: :componentes_index
  post 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_create'
  patch 'produto/componentes/:id1/:id2/:id3', to: 'produtos#componentes_update'
  get 'produto/componentes((/:id1)(/:id2)(/:id3))', to: 'produtos#componentes_show', as: :componentes_show
  get 'produtos/componentes_new', to: 'produtos#componentes_new', as: :componentes_new
  get 'produtos/componentes/:id1/:id2/:id3/edit', to: 'produtos#componentes_edit', as: :componentes_edit
  get 'produto/componentes/delcomponente/:id', to: 'produtos#componentes_destroy', as: :componentes_delete

end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  include ApplicationHelper
  before_action only: [:new, :create, :index, :update, :destroy] do redirecionar_privilegio(0) end
  before_action :privilegio_funcionario, only: [:show, :edit] 
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  def demitir
    @funcionario = Funcionario.find(params[:id])
    @funcionario.ativo = false
    respond_to do |format|
      if @funcionario.update(@funcionario.attributes)
        format.html { redirect_to @funcionario, notice: 'funcionario was successfully fired.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
    if (params[funcionarios_search_path].nil? ||
        params[funcionarios_search_path][:nome].empty?)
      nome = nil
    else
      nome = params[funcionarios_search_path][:nome]
    end
    if nome != nil
      @funcionarios = Funcionario.where("nome like '#{nome}'")
    else
      @funcionarios = Funcionario.all
    end
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def privilegio_funcionario
		redirecionar_privilegio(0) if(Funcionario.find(params[:id]) != current_funcionario)
	end
	# Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :cidade, :estado, :num, :endereco, :telefone, :salario, :dataContratacao, :ativo, :turno, :login, :password, :password_confirmation, :nivelAcesso)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>
<div class="portlet light">
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Listando Funcionarios</span>
    </div>
  </div>
  <div class="portlet-body">

    <%= render partial: 'table', locals: {funcionarios: @funcionarios } %>

    <br>

    <%= link_to  new_funcionario_path, class: "btn green" do %>
      <i class="fa fa-plus-circle"></i>
      New Funcionario
    <% end %>
    
    <%= link_to funcionarios_search_path, class: "btn green" do %>
      <i class="fa fa-search"></i>
      Consulta de funcionarios
    <% end %>
  </div>
</div>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<div class="portlet light">
  <div class="portlet-title">
    <div class="caption font-blue-sunglo">
      <span class="caption-subject bold uppercase">Mostrando Funcionario: <%= @funcionario.nome %></span>
    </div>
  </div>
  <div class="portlet-body">

    <p>
    <strong>Nome:</strong>
    <%= @funcionario.nome %>
    </p>

    <p>
    <strong>Cpf:</strong>
    <%= @funcionario.cpf %>
    </p>

    <p>
    <strong>Cidade:</strong>
    <%= @funcionario.cidade %>
    </p>

    <p>
    <strong>Estado:</strong>
    <%= @funcionario.estado %>
    </p>

    <p>
    <strong>Num:</strong>
    <%= @funcionario.num %>
    </p>

    <p>
    <strong>Endereco:</strong>
    <%= @funcionario.endereco %>
    </p>

    <p>
    <strong>Telefone:</strong>
    <%= @funcionario.telefone %>
    </p>

    <p>
    <strong>Salario:</strong>
    <%= @funcionario.salario %>
    </p>

    <p>
    <strong>Datacontratacao:</strong>
    <%= @funcionario.dataContratacao %>
    </p>

    <p>
    <strong>Ativo:</strong>
    <%= @funcionario.ativo %>
    </p>

    <p>
    <strong>Turno:</strong>
    <%= @funcionario.turno %>
    </p>

    <p>
    <strong>Login:</strong>
    <%= @funcionario.login %>
    </p>

    <p>
    <strong>Nivelacesso:</strong>
    <%= @funcionario.nivelAcesso %>
    </p>

    <%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
    <%= link_to 'Back', funcionarios_path %>

  </div>
</div>